birmingham =  [
 'Daniel Blake',
 'Ross Richesin',
 'Joseph Swing',
 'William Toranto',
 'Cameron DeArman',
 'Kamryn Bendolph',
 'Mitchell Henderson',
 'Joshua Hill',
 'Jacob Hoogstra',
 'Elliot Iturbe',
 'Andre Isaac Yu Tiamco',
 'Andrew Calkins',
 'Colette Crowder',
 'Wil Dotson',
 'Lorin Helfenstein',
 'Gerald Hudspeth',
 'Hayden Johnson',
 "Chandler O'Neal",
 'Bobby Oliver',
 'Griffin Riner',
 'John Simmons',
 'Warren Umbach',
 'Kyle Vosen',
 'Jordan Johnson',
 'Jordan Jones',
 'Killian Kahalley',
 'Clementine Lacey',
 'Peter Van Zandt',
 'Gabe Warner',
 'Mallory Wilson',
 'Will Cline',
 'Emma Choate',
 'Qiwen Ou',
 'Dorothy Alexander',
 'Lawrence Fountain',
 'Alexander Valencia'
]


